### ISSUE TITLE
The command does nothing (but exits successfully!)

### ISSUE THREAD

**Issue by cyrus-and** [ahmadnassri/har-cli#19]
```console
$ npm install --only=production --save @har/cli
[...]
$ node_modules/.bin/har
$ node_modules/.bin/har --help
$ node_modules/.bin/har validate
$ node_modules/.bin/har validate --help
```

The same happens installing globally.

- Linux
- Node.js v8.0.0-pre

**Comment by ahmadnassri** [comment]
- [x] investigating
- [x] commit fix
- [x] released in `v1.0.1`

**Comment by ahmadnassri** [comment]
Note: There is an issue in the Github Releases, they are not synced with NPM ... I'll look into this later.

published npm release should have the fix

**Comment by cyrus-and** [comment]
Awesome, the NPM version works as expected now. Thanks!
